---
title: "MissingDataImputation"
author: "Rachel Gordon"
date: "12/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <- read.csv("trainClassification.csv")
test <- read.csv("testClassification.csv")
```


```{r}
# replace missing data
# mean for numeric and mode for character variables

# replace with the mean
data$min_temp[is.na(data$min_temp)] <- mean(na.omit(data$min_temp))
data$max_temp[is.na(data$max_temp)] <- mean(na.omit(data$max_temp))
data$rainfall[is.na(data$rainfall)] <- mean(na.omit(data$rainfall))

# replace with the mode
data$evaporation[is.na(data$evaporation)] <- names(table(data$evaporation))[table(data$evaporation)==max(table(data$evaporation))]
data$sunshine[is.na(data$sunshine)] <- names(table(data$sunshine))[table(data$sunshine)==max(table(data$sunshine))]
data$wind_gust_dir[is.na(data$wind_gust_dir)] <- names(table(data$wind_gust_dir))[table(data$wind_gust_dir)==max(table(data$wind_gust_dir))]

# replace with the mean
data$wind_gust_speed[is.na(data$wind_gust_speed)] <- mean(na.omit(data$wind_gust_speed))

# replace with the mode
data$wind_dir9am[is.na(data$wind_dir9am)] <- names(table(data$wind_dir9am))[table(data$wind_dir9am)==max(table(data$wind_dir9am))]
data$wind_dir3pm[is.na(data$wind_dir3pm)] <- names(table(data$wind_dir3pm))[table(data$wind_dir3pm)==max(table(data$wind_dir3pm))]

# replace with the mean
data$wind_speed9am[is.na(data$wind_speed9am)] <- mean(na.omit(data$wind_speed9am))
data$wind_speed3pm[is.na(data$wind_speed3pm)] <- mean(na.omit(data$wind_speed3pm))
data$wind_speed9am[is.na(data$wind_speed9am)] <- mean(na.omit(data$wind_speed9am))
data$wind_speed3pm[is.na(data$wind_speed3pm)] <- mean(na.omit(data$wind_speed3pm))
data$humidity9am[is.na(data$humidity9am)] <- mean(na.omit(data$humidity9am))
data$humidity3pm[is.na(data$humidity3pm)] <- mean(na.omit(data$humidity3pm))
data$pressure9am[is.na(data$pressure9am)] <- mean(na.omit(data$pressure9am))
data$pressure3pm[is.na(data$pressure3pm)] <- mean(na.omit(data$pressure3pm))
data$cloud9am[is.na(data$cloud9am)] <- mean(na.omit(data$cloud9am))
data$cloud3pm[is.na(data$cloud3pm)] <- mean(na.omit(data$cloud3pm))
data$temp9am[is.na(data$temp9am)] <- mean(na.omit(data$temp9am))
data$temp3pm[is.na(data$temp3pm)] <- mean(na.omit(data$temp3pm))

# replace with the mode
data$rain_today[is.na(data$rain_today)] <- names(table(data$rain_today))[table(data$rain_today)==max(table(data$rain_today))]
```

```{r}
# encode train features as factor
data$rain_tomorrow <- as.factor(data$rain_tomorrow)
data$location <- as.factor(data$location)
data$evaporation <- as.factor(data$evaporation)
data$sunshine <- as.factor(data$sunshine)
data$wind_gust_dir <- as.factor(data$wind_gust_dir)
data$wind_dir9am <- as.factor(data$wind_dir9am)
data$wind_dir3pm <- as.factor(data$wind_dir3pm)
data$rain_today <- as.factor(data$rain_today)

# encode test set features as factor
test$location <- as.factor(test$location)
test$evaporation <- as.factor(test$evaporation)
test$sunshine <- as.factor(test$sunshine)
test$wind_gust_dir <- as.factor(test$wind_gust_dir)
test$wind_dir9am <- as.factor(test$wind_dir9am)
test$wind_dir3pm <- as.factor(test$wind_dir3pm)
test$rain_today <- as.factor(test$rain_today)
test$wind_gust_speed <- as.numeric(test$wind_gust_speed)
test$wind_speed9am <- as.numeric(test$wind_speed9am)
test$wind_speed3pm <- as.numeric(test$wind_speed3pm)
test$humidity9am <- as.numeric(test$humidity9am)
test$humidity3pm <- as.numeric(test$humidity3pm)
test$cloud9am <- as.numeric(test$cloud9am)
test$cloud3pm <- as.numeric(test$cloud3pm)

```



```{r}
# check missingness again
# percentage of missing values
missing_percent <- mean(is.na(data))
missing_percent
```


```{r}
# impute missing data
#library(mice)
#tempData <- mice(data,m=1,maxit=50,meth='pmm',seed=500)
#data <- complete(tempData,1)
```




```{r}
# train a random forest for train set

library(randomForest)

rf <- randomForest(
  as.factor(rain_tomorrow) ~ .,
  data = data, ntrees = 500
)

pred <- predict(rf, newdata=data)
cm <- table(data$rain_tomorrow, pred)
cm

n <- sum(cm)
diag <- diag(cm)

accuracy <- sum(diag)/n
accuracy
```

```{r}
# tune random forest for optimal mtry parameter

X_train_search <-subset(train_forest,select = -c(rain_tomorrow))
y_train_search <- train_forest$rain_tomorrow


rf_search <- tuneRF(X_train_search,y_train_search, stepFactor = 1, trace = TRUE, plot = TRUE, ntreeTry = 100)

```



```{r}

# train random forest and predict on test set with probabilities using optimal mtry

library(randomForest)


train_forest <- subset(data, select = c(location, min_temp, max_temp,rainfall, wind_gust_dir, wind_gust_speed,wind_dir9am, wind_dir3pm,wind_speed9am,wind_speed3pm, humidity9am,humidity3pm,pressure9am,pressure3pm,temp9am, temp3pm, rain_today,rain_tomorrow))

test_forest <- subset(test,select = c(location, min_temp, max_temp,rainfall, wind_gust_dir, wind_gust_speed,wind_dir9am, wind_dir3pm,wind_speed9am,wind_speed3pm, humidity9am,humidity3pm,pressure9am,pressure3pm,temp9am, temp3pm, rain_today))

test_forest$rain_tomorrow <- rep(1, nrow(test_forest))

rf <- randomForest(rain_tomorrow~., data = train_forest, ntrees = 1000, mtry = 4)

pred <- predict(rf, test_forest, type = "prob")
pred

answer <- data.frame(test$id, pred)

answer_final = subset(answer, select = c(test.id, X1))
names(answer_final)[1] <- "id"
names(answer_final)[2] <- "rain_tomorrow"
answer_final

```



```{r}
# feature importance with gbm
# create a general boosted model and output predictions for test set
train_gbm <- train_forest[,]
levels(train_gbm$rain_today) <- c("0", "1")
levels(train_gbm$rain_tomorrow) <- c("0", "1")
train_gbm$rain_today <- as.factor(train_gbm$rain_today)
train_gbm$rain_tomorrow <- as.character(train_gbm$rain_tomorrow)

library(gbm)

model <- gbm(as.numeric(rain_tomorrow)~., distribution = "bernoulli", n.trees = 500, data = train_gbm)

summary(model)

pred <- predict(model,test_forest, type = "response")


gbm_ans <- data.frame(test$id,pred)


names(gbm_ans)[1] <- "id"
names(gbm_ans)[2] <- "rain_tomorrow"

gbm_ans

```




