---
title: "svm_classification"
author: "Aldrich Paras"
date: "12/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <- read.csv("trainClassification.csv")
test <- read.csv("testClassification.csv")
```


```{r}
# replace missing data
# mean for numeric and mode for character variables

# replace with the mean
data$min_temp[is.na(data$min_temp)] <- mean(na.omit(data$min_temp))
data$max_temp[is.na(data$max_temp)] <- mean(na.omit(data$max_temp))
data$rainfall[is.na(data$rainfall)] <- mean(na.omit(data$rainfall))

# replace with the mode
data$evaporation[is.na(data$evaporation)] <- names(table(data$evaporation))[table(data$evaporation)==max(table(data$evaporation))]
data$sunshine[is.na(data$sunshine)] <- names(table(data$sunshine))[table(data$sunshine)==max(table(data$sunshine))]
data$wind_gust_dir[is.na(data$wind_gust_dir)] <- names(table(data$wind_gust_dir))[table(data$wind_gust_dir)==max(table(data$wind_gust_dir))]

# replace with the mean
data$wind_gust_speed[is.na(data$wind_gust_speed)] <- mean(na.omit(data$wind_gust_speed))

# replace with the mode
data$wind_dir9am[is.na(data$wind_dir9am)] <- names(table(data$wind_dir9am))[table(data$wind_dir9am)==max(table(data$wind_dir9am))]
data$wind_dir3pm[is.na(data$wind_dir3pm)] <- names(table(data$wind_dir3pm))[table(data$wind_dir3pm)==max(table(data$wind_dir3pm))]

# replace with the mean
data$wind_speed9am[is.na(data$wind_speed9am)] <- mean(na.omit(data$wind_speed9am))
data$wind_speed3pm[is.na(data$wind_speed3pm)] <- mean(na.omit(data$wind_speed3pm))
data$wind_speed9am[is.na(data$wind_speed9am)] <- mean(na.omit(data$wind_speed9am))
data$wind_speed3pm[is.na(data$wind_speed3pm)] <- mean(na.omit(data$wind_speed3pm))
data$humidity9am[is.na(data$humidity9am)] <- mean(na.omit(data$humidity9am))
data$humidity3pm[is.na(data$humidity3pm)] <- mean(na.omit(data$humidity3pm))
data$pressure9am[is.na(data$pressure9am)] <- mean(na.omit(data$pressure9am))
data$pressure3pm[is.na(data$pressure3pm)] <- mean(na.omit(data$pressure3pm))
data$cloud9am[is.na(data$cloud9am)] <- mean(na.omit(data$cloud9am))
data$cloud3pm[is.na(data$cloud3pm)] <- mean(na.omit(data$cloud3pm))
data$temp9am[is.na(data$temp9am)] <- mean(na.omit(data$temp9am))
data$temp3pm[is.na(data$temp3pm)] <- mean(na.omit(data$temp3pm))

# replace with the mode
data$rain_today[is.na(data$rain_today)] <- names(table(data$rain_today))[table(data$rain_today)==max(table(data$rain_today))]
```

```{r}
# encode trian features as factor
data$rain_tomorrow <- as.factor(data$rain_tomorrow)
data$location <- as.factor(data$location)
data$evaporation <- as.factor(data$evaporation)
data$sunshine <- as.factor(data$sunshine)
data$wind_gust_dir <- as.factor(data$wind_gust_dir)
data$wind_dir9am <- as.factor(data$wind_dir9am)
data$wind_dir3pm <- as.factor(data$wind_dir3pm)
data$rain_today <- as.factor(data$rain_today)

# encode test set features as factor
test$location <- as.factor(test$location)
test$evaporation <- as.factor(test$evaporation)
test$sunshine <- as.factor(test$sunshine)
test$wind_gust_dir <- as.factor(test$wind_gust_dir)
test$wind_dir9am <- as.factor(test$wind_dir9am)
test$wind_dir3pm <- as.factor(test$wind_dir3pm)
test$rain_today <- as.factor(test$rain_today)
test$wind_gust_speed <- as.numeric(test$wind_gust_speed)
test$wind_speed9am <- as.numeric(test$wind_speed9am)
test$wind_speed3pm <- as.numeric(test$wind_speed3pm)
test$humidity9am <- as.numeric(test$humidity9am)
test$humidity3pm <- as.numeric(test$humidity3pm)
test$cloud9am <- as.numeric(test$cloud9am)
test$cloud3pm <- as.numeric(test$cloud3pm)


# subset
train <- data[,]
#train <- data[,(3:24)]
#test <- test[,(3:23)]
```



```{r}
# feature importance with gbm

library(gbm)

model <- gbm(rain_tomorrow~.-id-date, distribution = "gaussian", n.trees = 1000, data = data)
summary(model)
```





```{r}
#### DONT RUN TAKES A LONG TIME TO RUN #####
# train svm 
library(e1071)

# create dev set
set.seed(123)
index <- sample(seq_len(nrow(train)), size = nrow(train)*.8)

X_train <- train[index, ]

X_dev <- train[-index, ]

# find best hyperparameters
svm_search <-  tune(svm, rain_tomorrow~., data = X_train, ranges=list(cost=c(0.01,.1,1,10,100), kernel = c("radial","linear")))
summary(svm_search)
```

```{r}
# test on dev set 

table(predict(svm_search,X_dev), X_dev$rain_tomorrow, dnn=c("Prediction", "Actual"))
```

```{r}

## RUN THIS AS IT HAS OPTIMAL PARAMETERS
# final svm

svm_final <- svm(rain_tomorrow~., data = train, cost = 10, kernel = "radial", probability=TRUE)

pred <- predict(svm_final, train, probability = TRUE)

pred
table(predict(svm_final,train), train$rain_tomorrow, dnn=c("Prediction", "Actual"))
```





