---
title: "EDARegression"
author: "Rachel Gordon"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import data
data <- read.csv("Regression/trainRegression.csv")
```

```{r}
# calculate 5 number summary for each variable
summary(data)
```

```{r}
# Calculate missing counts for each variable
name_missing <-  sum(is.na(data["name"]))
host_id_missing <- sum(is.na(data["host_id"]))
host_name_missing <-  sum(is.na(data["host_name"]))
neighbourhood_group_missing <-  sum(is.na(data["neighbourhood_group"]))
neighbourhood_missing <- sum(is.na(data["neighbourhood"]))
latitude_missing <-  sum(is.na(data["latitude"]))
longitude_missing <- sum(is.na(data["longitude"]))
room_type_missing <- sum(is.na(data["room_type"]))
price_missing <- sum(is.na(data["price"]))
minimum_nights_missing <- sum(is.na(data["minimum_nights"]))
number_of_reviews_missing <- sum(is.na(data["number_of_reviews"]))
last_review_missing <- sum(is.na(data["last_review"]))
reviews_per_month_missing <- sum(is.na(data["reviews_per_month"]))
calculated_host_listings_count_missing <- sum(is.na(data["calculated_host_listings_count"]))
availability_365_missing <- sum(is.na(data["availability_365"]))

name_missing
host_id_missing
host_name_missing
neighbourhood_group_missing
neighbourhood_missing
latitude_missing
longitude_missing
room_type_missing
price_missing
minimum_nights_missing
number_of_reviews_missing
last_review_missing
reviews_per_month_missing
calculated_host_listings_count_missing
availability_365_missing

# percentage of missing values
missing_percent <- mean(is.na(data))
missing_percent
```

name - 9 Missing
host_id - 0 Missing
host_name - 14 Missing
neighbourhood_group - 0 Missing
neighbourhood - 0 Missing
latitude - 0 Missing
longitude - 0 Missing
room_type - 0 Missing
price - 0 Missing
minimum_nights - 0 Missing
number_of_reviews - 0 Missing
last_review - 7008 Missing
reviews_per_month - 7008 Missing
calculated_host_listings_count - 0 Missing
availability_365 - 0 Missing

~ 2.56% of data is missing


```{r}
# count information and graphs for variables
library(ggplot2)

# Location counts
ggplot(data, aes(x = location))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip()+ggtitle("Location")

# min_temp counts
ggplot(data, aes(x = min_temp))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip()+ggtitle("Min Temp")

# max_temp counts
ggplot(data, aes(x = max_temp))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip()+ggtitle("Max Temp")

# rainfall counts
ggplot(data, aes(x = rainfall))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Rainfall") + xlim(0,15) + ylim(0,100)

# evaporation counts
ggplot(data, aes(x = evaporation))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Evaporation") 

# sunshine counts
ggplot(data, aes(x = sunshine))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Sunshine") 

# wind gust direction counts
ggplot(data, aes(x = wind_gust_dir))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Gust Direction") 

# Wind Gust Speed counts
ggplot(data, aes(x = wind_gust_speed))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Gust Speed") 

# Wind Direction 9 am
ggplot(data, aes(x = wind_dir9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Direction 9 am") 

# Wind Direction3 pm
ggplot(data, aes(x = wind_dir3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Direction 3 pm") 

# Wind Speed 9 am
ggplot(data, aes(x = wind_speed9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Speed 9 am") 

# Wind Speed 3 pm
ggplot(data, aes(x = wind_speed3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Wind Speed 3 pm") 

# Humidity 9 am
ggplot(data, aes(x = humidity9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Humidity 9 am") 

# Humidity 3 pm
ggplot(data, aes(x = humidity3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Humidity 3 pm") 

# Pressure 9 am
ggplot(data, aes(x = pressure9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Pressure 9 am") 

# Pressure 3 pm
ggplot(data, aes(x = pressure3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Pressure 3 pm") 

# Cloud 9 am
ggplot(data, aes(x = cloud9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Cloud 9 am") 

# Cloud 3 pm
ggplot(data, aes(x = cloud3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Cloud 3 pm")

# Temp 9 am
ggplot(data, aes(x = temp9am))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Temp 9 am")

# Temp 3 pm
ggplot(data, aes(x = temp3pm))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Temp 3 pm")

# rain today
ggplot(data, aes(x = rain_today))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Rain Today")

# rain tomorrow
ggplot(data, aes(x = rain_tomorrow))+ geom_histogram(stat = "count", fill = "tomato2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + coord_flip() +ggtitle("Rain Tomorrow")
```

